/*
 * This file is generated by jOOQ.
 */
package ru.otus.kotlin.course.repo.postgre.tables.records


import org.jooq.impl.TableRecordImpl

import ru.otus.kotlin.course.repo.postgre.tables.Files


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class FilesRecord() : TableRecordImpl<FilesRecord>(Files.FILES) {

    open var imageId: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var `data`: ByteArray?
        set(value): Unit = set(1, value)
        get(): ByteArray? = get(1) as ByteArray?

    /**
     * Create a detached, initialised FilesRecord
     */
    constructor(imageId: String? = null, `data`: ByteArray? = null): this() {
        this.imageId = imageId
        this.`data` = `data`
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised FilesRecord
     */
    constructor(value: ru.otus.kotlin.course.repo.postgre.tables.pojos.Files?): this() {
        if (value != null) {
            this.imageId = value.imageId
            this.`data` = value.`data`
            resetChangedOnNotNull()
        }
    }
}
