/*
 * This file is generated by jOOQ.
 */
package ru.otus.kotlin.course.repo.postgre.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

import ru.otus.kotlin.course.repo.postgre.tables.Images


/**
 * Изображения
 */
@Suppress("UNCHECKED_CAST")
open class ImagesRecord() : UpdatableRecordImpl<ImagesRecord>(Images.IMAGES) {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var title: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var description: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var uploadurl: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var imageurl: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var previewurl: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var permanentlinkurl: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ImagesRecord
     */
    constructor(id: String? = null, title: String? = null, description: String? = null, uploadurl: String? = null, imageurl: String? = null, previewurl: String? = null, permanentlinkurl: String? = null): this() {
        this.id = id
        this.title = title
        this.description = description
        this.uploadurl = uploadurl
        this.imageurl = imageurl
        this.previewurl = previewurl
        this.permanentlinkurl = permanentlinkurl
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised ImagesRecord
     */
    constructor(value: ru.otus.kotlin.course.repo.postgre.tables.pojos.Images?): this() {
        if (value != null) {
            this.id = value.id
            this.title = value.title
            this.description = value.description
            this.uploadurl = value.uploadurl
            this.imageurl = value.imageurl
            this.previewurl = value.previewurl
            this.permanentlinkurl = value.permanentlinkurl
            resetChangedOnNotNull()
        }
    }
}
