/*
 * This file is generated by jOOQ.
 */
package ru.otus.kotlin.course.repo.postgre.tables.records


import org.jooq.impl.TableRecordImpl

import ru.otus.kotlin.course.repo.postgre.tables.LabelValues


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class LabelValuesRecord() : TableRecordImpl<LabelValuesRecord>(LabelValues.LABEL_VALUES) {

    open var labelKey: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var imageId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var value: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    /**
     * Create a detached, initialised LabelValuesRecord
     */
    constructor(labelKey: String? = null, imageId: String? = null, value: String? = null): this() {
        this.labelKey = labelKey
        this.imageId = imageId
        this.value = value
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised LabelValuesRecord
     */
    constructor(value: ru.otus.kotlin.course.repo.postgre.tables.pojos.LabelValues?): this() {
        if (value != null) {
            this.labelKey = value.labelKey
            this.imageId = value.imageId
            this.value = value.value
            resetChangedOnNotNull()
        }
    }
}
