/*
 * This file is generated by jOOQ.
 */
package ru.otus.kotlin.course.repo.postgre.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

import ru.otus.kotlin.course.repo.postgre.tables.Labels


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class LabelsRecord() : UpdatableRecordImpl<LabelsRecord>(Labels.LABELS) {

    open var key: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var description: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised LabelsRecord
     */
    constructor(key: String? = null, description: String? = null): this() {
        this.key = key
        this.description = description
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised LabelsRecord
     */
    constructor(value: ru.otus.kotlin.course.repo.postgre.tables.pojos.Labels?): this() {
        if (value != null) {
            this.key = value.key
            this.description = value.description
            resetChangedOnNotNull()
        }
    }
}
