/*
 * This file is generated by jOOQ.
 */
package ru.otus.kotlin.course.repo.postgre.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

import ru.otus.kotlin.course.repo.postgre.tables.Tags


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TagsRecord() : UpdatableRecordImpl<TagsRecord>(Tags.TAGS) {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var value: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var imageId: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised TagsRecord
     */
    constructor(id: String? = null, value: String? = null, imageId: String? = null): this() {
        this.id = id
        this.value = value
        this.imageId = imageId
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised TagsRecord
     */
    constructor(value: ru.otus.kotlin.course.repo.postgre.tables.pojos.Tags?): this() {
        if (value != null) {
            this.id = value.id
            this.value = value.value
            this.imageId = value.imageId
            resetChangedOnNotNull()
        }
    }
}
