/*
 * This file is generated by jOOQ.
 */
package ru.otus.kotlin.course.repo.postgre.keys


import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal

import ru.otus.kotlin.course.repo.postgre.tables.Files
import ru.otus.kotlin.course.repo.postgre.tables.Images
import ru.otus.kotlin.course.repo.postgre.tables.LabelValues
import ru.otus.kotlin.course.repo.postgre.tables.Labels
import ru.otus.kotlin.course.repo.postgre.tables.Tags
import ru.otus.kotlin.course.repo.postgre.tables.records.FilesRecord
import ru.otus.kotlin.course.repo.postgre.tables.records.ImagesRecord
import ru.otus.kotlin.course.repo.postgre.tables.records.LabelValuesRecord
import ru.otus.kotlin.course.repo.postgre.tables.records.LabelsRecord
import ru.otus.kotlin.course.repo.postgre.tables.records.TagsRecord



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val UQ_FILES_KEY: UniqueKey<FilesRecord> = Internal.createUniqueKey(Files.FILES, DSL.name("uq_files_key"), arrayOf(Files.FILES.IMAGE_ID), true)
val IMAGE_PK: UniqueKey<ImagesRecord> = Internal.createUniqueKey(Images.IMAGES, DSL.name("image_pk"), arrayOf(Images.IMAGES.ID), true)
val UK_LABEL_VALUE: UniqueKey<LabelValuesRecord> = Internal.createUniqueKey(LabelValues.LABEL_VALUES, DSL.name("uk_label_value"), arrayOf(LabelValues.LABEL_VALUES.LABEL_KEY, LabelValues.LABEL_VALUES.IMAGE_ID), true)
val LABELS_PKEY: UniqueKey<LabelsRecord> = Internal.createUniqueKey(Labels.LABELS, DSL.name("labels_pkey"), arrayOf(Labels.LABELS.KEY), true)
val UQ_LABELS_KEY: UniqueKey<LabelsRecord> = Internal.createUniqueKey(Labels.LABELS, DSL.name("uq_labels_key"), arrayOf(Labels.LABELS.KEY), true)
val TAGS_PKEY: UniqueKey<TagsRecord> = Internal.createUniqueKey(Tags.TAGS, DSL.name("tags_pkey"), arrayOf(Tags.TAGS.ID), true)
