/*
 * This file is generated by jOOQ.
 */
package ru.otus.kotlin.course.repo.postgre.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import ru.otus.kotlin.course.repo.postgre.Public
import ru.otus.kotlin.course.repo.postgre.indexes.IX_IMAGESTITLE
import ru.otus.kotlin.course.repo.postgre.keys.IMAGE_PK
import ru.otus.kotlin.course.repo.postgre.tables.records.ImagesRecord


/**
 * Изображения
 */
@Suppress("UNCHECKED_CAST")
open class Images(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ImagesRecord>?,
    parentPath: InverseForeignKey<out Record, ImagesRecord>?,
    aliased: Table<ImagesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ImagesRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment("Изображения"),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.images</code>
         */
        val IMAGES: Images = Images()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ImagesRecord> = ImagesRecord::class.java

    /**
     * The column <code>public.images.id</code>.
     */
    val ID: TableField<ImagesRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>public.images.title</code>.
     */
    val TITLE: TableField<ImagesRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(254), this, "")

    /**
     * The column <code>public.images.description</code>.
     */
    val DESCRIPTION: TableField<ImagesRecord, String?> = createField(DSL.name("description"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.images.uploadUrl</code>. Ссылка на изображение
     * при загрузке
     */
    val UPLOADURL: TableField<ImagesRecord, String?> = createField(DSL.name("uploadUrl"), SQLDataType.VARCHAR(1024), this, "Ссылка на изображение при загрузке")

    /**
     * The column <code>public.images.imageUrl</code>. Ссылка на изображение
     */
    val IMAGEURL: TableField<ImagesRecord, String?> = createField(DSL.name("imageUrl"), SQLDataType.VARCHAR(1024), this, "Ссылка на изображение")

    /**
     * The column <code>public.images.previewUrl</code>. Ссылка на preview
     */
    val PREVIEWURL: TableField<ImagesRecord, String?> = createField(DSL.name("previewUrl"), SQLDataType.VARCHAR(1024), this, "Ссылка на preview")

    /**
     * The column <code>public.images.permanentLinkUrl</code>. Ссылка на
     * постоянную локацию изображения
     */
    val PERMANENTLINKURL: TableField<ImagesRecord, String?> = createField(DSL.name("permanentLinkUrl"), SQLDataType.VARCHAR(1024), this, "Ссылка на постоянную локацию изображения")

    private constructor(alias: Name, aliased: Table<ImagesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ImagesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ImagesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.images</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.images</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.images</code> table reference
     */
    constructor(): this(DSL.name("images"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IX_IMAGESTITLE)
    override fun getPrimaryKey(): UniqueKey<ImagesRecord> = IMAGE_PK
    override fun `as`(alias: String): Images = Images(DSL.name(alias), this)
    override fun `as`(alias: Name): Images = Images(alias, this)
    override fun `as`(alias: Table<*>): Images = Images(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Images = Images(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Images = Images(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Images = Images(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Images = Images(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Images = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Images = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Images = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Images = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Images = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Images = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Images = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Images = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Images = where(DSL.notExists(select))
}
