/*
 * This file is generated by jOOQ.
 */
package ru.otus.kotlin.course.repo.postgre.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import ru.otus.kotlin.course.repo.postgre.Public
import ru.otus.kotlin.course.repo.postgre.keys.LABELS_PKEY
import ru.otus.kotlin.course.repo.postgre.keys.UQ_LABELS_KEY
import ru.otus.kotlin.course.repo.postgre.tables.records.LabelsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Labels(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, LabelsRecord>?,
    parentPath: InverseForeignKey<out Record, LabelsRecord>?,
    aliased: Table<LabelsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<LabelsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.labels</code>
         */
        val LABELS: Labels = Labels()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<LabelsRecord> = LabelsRecord::class.java

    /**
     * The column <code>public.labels.key</code>.
     */
    val KEY: TableField<LabelsRecord, String?> = createField(DSL.name("key"), SQLDataType.VARCHAR(32).nullable(false), this, "")

    /**
     * The column <code>public.labels.description</code>.
     */
    val DESCRIPTION: TableField<LabelsRecord, String?> = createField(DSL.name("description"), SQLDataType.CLOB, this, "")

    private constructor(alias: Name, aliased: Table<LabelsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<LabelsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<LabelsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.labels</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.labels</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.labels</code> table reference
     */
    constructor(): this(DSL.name("labels"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<LabelsRecord> = LABELS_PKEY
    override fun getUniqueKeys(): List<UniqueKey<LabelsRecord>> = listOf(UQ_LABELS_KEY)
    override fun `as`(alias: String): Labels = Labels(DSL.name(alias), this)
    override fun `as`(alias: Name): Labels = Labels(alias, this)
    override fun `as`(alias: Table<*>): Labels = Labels(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Labels = Labels(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Labels = Labels(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Labels = Labels(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Labels = Labels(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Labels = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Labels = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Labels = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Labels = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Labels = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Labels = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Labels = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Labels = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Labels = where(DSL.notExists(select))
}
