/*
 * This file is generated by jOOQ.
 */
package ru.otus.kotlin.course.repo.postgre.tables.pojos


import java.io.Serializable
import java.util.Arrays


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Files(
    var imageId: String,
    var `data`: ByteArray? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Files = other as Files
        if (this.imageId != o.imageId)
            return false
        if (this.`data` == null) {
            if (o.`data` != null)
                return false
        }
        else if (!Arrays.equals(this.`data`, o.`data`))
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.imageId.hashCode()
        result = prime * result + (if (this.`data` == null) 0 else Arrays.hashCode(this.`data`))
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Files (")

        sb.append(imageId)
        sb.append(", ").append("[binary...]")

        sb.append(")")
        return sb.toString()
    }
}
