/*
 * This file is generated by jOOQ.
 */
package ru.otus.kotlin.course.repo.postgre.tables.pojos


import java.io.Serializable


/**
 * Изображения
 */
@Suppress("UNCHECKED_CAST")
data class Images(
    var id: String,
    var title: String? = null,
    var description: String? = null,
    var uploadurl: String? = null,
    var imageurl: String? = null,
    var previewurl: String? = null,
    var permanentlinkurl: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Images = other as Images
        if (this.id != o.id)
            return false
        if (this.title == null) {
            if (o.title != null)
                return false
        }
        else if (this.title != o.title)
            return false
        if (this.description == null) {
            if (o.description != null)
                return false
        }
        else if (this.description != o.description)
            return false
        if (this.uploadurl == null) {
            if (o.uploadurl != null)
                return false
        }
        else if (this.uploadurl != o.uploadurl)
            return false
        if (this.imageurl == null) {
            if (o.imageurl != null)
                return false
        }
        else if (this.imageurl != o.imageurl)
            return false
        if (this.previewurl == null) {
            if (o.previewurl != null)
                return false
        }
        else if (this.previewurl != o.previewurl)
            return false
        if (this.permanentlinkurl == null) {
            if (o.permanentlinkurl != null)
                return false
        }
        else if (this.permanentlinkurl != o.permanentlinkurl)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + (if (this.title == null) 0 else this.title.hashCode())
        result = prime * result + (if (this.description == null) 0 else this.description.hashCode())
        result = prime * result + (if (this.uploadurl == null) 0 else this.uploadurl.hashCode())
        result = prime * result + (if (this.imageurl == null) 0 else this.imageurl.hashCode())
        result = prime * result + (if (this.previewurl == null) 0 else this.previewurl.hashCode())
        result = prime * result + (if (this.permanentlinkurl == null) 0 else this.permanentlinkurl.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Images (")

        sb.append(id)
        sb.append(", ").append(title)
        sb.append(", ").append(description)
        sb.append(", ").append(uploadurl)
        sb.append(", ").append(imageurl)
        sb.append(", ").append(previewurl)
        sb.append(", ").append(permanentlinkurl)

        sb.append(")")
        return sb.toString()
    }
}
