/*
 * This file is generated by jOOQ.
 */
package ru.otus.kotlin.course.repo.postgre.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class LabelValues(
    var labelKey: String,
    var imageId: String,
    var value: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: LabelValues = other as LabelValues
        if (this.labelKey != o.labelKey)
            return false
        if (this.imageId != o.imageId)
            return false
        if (this.value == null) {
            if (o.value != null)
                return false
        }
        else if (this.value != o.value)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.labelKey.hashCode()
        result = prime * result + this.imageId.hashCode()
        result = prime * result + (if (this.value == null) 0 else this.value.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("LabelValues (")

        sb.append(labelKey)
        sb.append(", ").append(imageId)
        sb.append(", ").append(value)

        sb.append(")")
        return sb.toString()
    }
}
