/*
 * This file is generated by jOOQ.
 */
package ru.otus.kotlin.course.repo.postgre.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Labels(
    var key: String,
    var description: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Labels = other as Labels
        if (this.key != o.key)
            return false
        if (this.description == null) {
            if (o.description != null)
                return false
        }
        else if (this.description != o.description)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.key.hashCode()
        result = prime * result + (if (this.description == null) 0 else this.description.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Labels (")

        sb.append(key)
        sb.append(", ").append(description)

        sb.append(")")
        return sb.toString()
    }
}
