/*
 * This file is generated by jOOQ.
 */
package ru.otus.kotlin.course.repo.postgre.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Tags(
    var id: String,
    var value: String,
    var imageId: String
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Tags = other as Tags
        if (this.id != o.id)
            return false
        if (this.value != o.value)
            return false
        if (this.imageId != o.imageId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.value.hashCode()
        result = prime * result + this.imageId.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Tags (")

        sb.append(id)
        sb.append(", ").append(value)
        sb.append(", ").append(imageId)

        sb.append(")")
        return sb.toString()
    }
}
