/*
 * This file is generated by jOOQ.
 */
package ru.otus.kotlin.course.repo.postgre.indexes


import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal

import ru.otus.kotlin.course.repo.postgre.tables.Files
import ru.otus.kotlin.course.repo.postgre.tables.Images



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IX_FILES_IMAGES_ID: Index = Internal.createIndex(DSL.name("ix_files_images_id"), Files.FILES, arrayOf(Files.FILES.IMAGE_ID), false)
val IX_IMAGESTITLE: Index = Internal.createIndex(DSL.name("ix_imagestitle"), Images.IMAGES, arrayOf(Images.IMAGES.TITLE), false)
