/*
 * This file is generated by jOOQ.
 */
package ru.otus.kotlin.course.repo.postgre.tables.references


import ru.otus.kotlin.course.repo.postgre.tables.Files
import ru.otus.kotlin.course.repo.postgre.tables.Images
import ru.otus.kotlin.course.repo.postgre.tables.LabelValues
import ru.otus.kotlin.course.repo.postgre.tables.Labels
import ru.otus.kotlin.course.repo.postgre.tables.Tags



/**
 * The table <code>public.files</code>.
 */
val FILES: Files = Files.FILES

/**
 * Изображения
 */
val IMAGES: Images = Images.IMAGES

/**
 * The table <code>public.label_values</code>.
 */
val LABEL_VALUES: LabelValues = LabelValues.LABEL_VALUES

/**
 * The table <code>public.labels</code>.
 */
val LABELS: Labels = Labels.LABELS

/**
 * The table <code>public.tags</code>.
 */
val TAGS: Tags = Tags.TAGS
