/*
 * This file is generated by jOOQ.
 */
package ru.otus.kotlin.course.repo.postgre


import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl

import ru.otus.kotlin.course.repo.postgre.tables.Files
import ru.otus.kotlin.course.repo.postgre.tables.Images
import ru.otus.kotlin.course.repo.postgre.tables.LabelValues
import ru.otus.kotlin.course.repo.postgre.tables.Labels
import ru.otus.kotlin.course.repo.postgre.tables.Tags


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.files</code>.
     */
    val FILES: Files get() = Files.FILES

    /**
     * Изображения
     */
    val IMAGES: Images get() = Images.IMAGES

    /**
     * The table <code>public.label_values</code>.
     */
    val LABEL_VALUES: LabelValues get() = LabelValues.LABEL_VALUES

    /**
     * The table <code>public.labels</code>.
     */
    val LABELS: Labels get() = Labels.LABELS

    /**
     * The table <code>public.tags</code>.
     */
    val TAGS: Tags get() = Tags.TAGS

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Files.FILES,
        Images.IMAGES,
        LabelValues.LABEL_VALUES,
        Labels.LABELS,
        Tags.TAGS
    )
}
